{
    'name': 'Local LC Sales Function',
    'author': 'Genweb2 Limited',
    'website': 'www.genweb2.com',
    'category': 'Commercial',
    'version':'10.0.1.0.0',
    'depends': [
        'lc_sales_product',
    ],

    'data': [
        'views/lc_sales_view.xml',
        'views/shipment_sale_view.xml',
        'views/lc_sales_commercial.xml',
        'reports/bank_top_sheet.xml',
        'reports/bill_of_exchange_first_report.xml',
        'reports/bill_of_exchange_second_report.xml',
        'reports/commercial_invoice_report_view.xml',
        'reports/beneficiary_certificate.xml',
        'reports/packing_list_report_view.xml',
        'reports/measurement_list_report.xml',
        'reports/party_receiving_sheet.xml',
        'reports/certificate_of_origin.xml',
        'reports/inspection_certificate.xml',
        'reports/delivery_challan_report.xml',
        'reports/truck_receipt_report.xml',
        'wizard/doc_receive_wizard_view.xml',
        'wizard/lc_sales_report_wizard.xml',
        'wizard/sales_export_wizard_view.xml',
        'wizard/buyer_export_wizard_view.xml',
        'wizard/seller_bank_export_wizard_view.xml',
        'wizard/buyer_bank_export_wizard_view.xml',
        'wizard/maturity_export_wizard_view.xml',
        'wizard/lc_amendment_wizard_view.xml',
        'wizard/sales_invoice_export_wizard_view.xml',
        'views/lc_sales_comm_acc.xml',
        'views/lc_sales_menu.xml',
    ],

    'summary': 'Sale By LC',
    'installable': True,
    'application': False,
    'auto_install': True
}