# -*- coding: utf-8 -*-

{
    'name': 'EMK HR Installation',
    'author': 'Genweb2 Limited',
    'website': 'www.genweb2.com',
    'category': 'EMK HR Installation',
    'version': '10.0.1.0.0',
    'data': [],
    'depends': [
        'gbs_hr_attendance_report',
        'gbs_hr_employee_security',
        'gbs_hr_employee_sequence',
        # 'gbs_hr_job_confirmation',
        # 'gbs_hr_leave_duration_correction',
        'gbs_hr_leave_report',
        'gbs_hr_payroll',
        'gbs_hr_public_holidays',
        'gbs_hr_recruitment',
        'gbs_operating_unit',
        'gbs_hr_holiday_hour',
        # 'gbs_hr_evaluation',
        'hr_attendance_and_ot_summary',
        # 'hr_attendance_dashboard',
        'hr_attendance_settings',
        'hr_earned_leave',
        'hr_employee_attendance_payroll',
        'hr_employee_iou_payroll',
        'hr_employee_meal_bills_payroll',
        'hr_employee_mobile_bills_payroll',
        'hr_employee_number',
        'hr_employee_operating_unit',
        'hr_holidays_multi_approval_notification',
        'hr_holidays_multi_levels_approval',
        'hr_leave_carry_forward',
        'hr_leave_encashment',
        'hr_manual_attendance',
        'hr_payroll_arrear',
        'hr_recruitment_survey',
        'hr_short_leave',
        'hr_experience',
        'hr_contract_reference',
        'hr_security',
        'hr_experience_extend',
        'emk_hr',
        'website_job_application',
        'gbs_employee_roster_view',
    ],
    'category': 'Installation Module',
    'summary': 'Install Module of EMK',
    'description': 'Install Module of EMK',
    'installable': True,
    'application': True,
}
