# -*- coding: utf-8 -*-

{
    'name': 'EMK HR Installation',
    'author': 'Genweb2 Limited',
    'website': 'www.genweb2.com',
    'category': 'EMK HR Installation',
    'version': '10.0.1.0.0',
    'data': [],
    'depends': [
        'emk_hr',
        'gbs_hr_payroll',
        'gbs_hr_payroll_bank_letter',
        'gbs_hr_payroll_top_sheet',
        'gbs_hr_attendance_report',
        'gbs_hr_leave_report',
        'gbs_employee_roster_view',
        'hr_attendance_and_ot_summary',
        'hr_attendance_dashboard',
        'hr_manual_attendance',
        'hr_employee_attendance_payroll',
        'hr_employee_mobile_bills_payroll',
        'hr_employee_meal_bills_payroll',
        'hr_other_allowance_payroll',
        'hr_other_allowance_payroll',
        'hr_payroll_arrear',
        'hr_earned_leave',
        'hr_recruitment_survey',
        'gbs_base_package',
        'gbs_hr_package',
        'hr_holiday_utility',
        'hr_holidays_multi_approval_notification',
        'base_suspend_security',
        'base_bank_bd',
        'gbs_hr_employee_security',
        'ir_sequence_operating_unit',
        'gbs_hr_public_holidays',
        'gbs_hr_leave_duration_correction',
        'gbs_hr_security',
        'hr_family',
        'hr_contract_reference',
        'hr_employee_iou_payroll',
        'hr_employee_number',
        'hr_employee_exit',
        'hr_employee_number',
        'website_hr_recruitment'

    ],
    'category': 'Installation Module',
    'summary': 'Install Module of EMK',
    'description': 'Install Module of EMK',
    'installable': True,
    'application': True,
}
