$axure.loadCurrentPage({
  "url":"task_1.html",
  "generationDate":new Date(1462978072147.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NotesSA"],
  "defaultBackgroundImageInfo":{
    "path":"images/production_planning/bg.jpg",
    "width":1440,
    "height":960},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"aed208c0c4e947edac220c61d5cefc1b",
    "type":"Axure:Page",
    "name":"Task",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bc187aae2b104b498d0c473cc96c85c6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"614f077af181494a913dda5407de8b37"},
{
          "id":"f166583c2c20436987b0cc4b33e8875f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":104},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c183bd4271a48dbb376a715ec557a6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":104},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67e4d6cd63fc4b229bdfd5de6db9771f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":100},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"da186554ecef4ea2a90d0720d2789d3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":173},
            "size":{
              "width":128,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2f51e3e8c4e42a881ac38621b838691",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":173},
                "size":{
                  "width":128,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1cd98109a0f648bd8daa27f147d51b99",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":170},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"1d5ce1f717f245c0ac1fdeecdfa7835e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":138},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0798e04d543c492e8b7fbc00be01e3db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":138},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83a89eb7a6224c8c9c52fcd8bb2f865c",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":135},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"548568981fc44d3a95ec0e75adb8c475",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":415,
              "y":98},
            "size":{
              "width":145,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fabacb0a7a34488695312318534a1a4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":415,
                  "y":98},
                "size":{
                  "width":145,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/task_1/u26.png"}},
{
          "id":"2bbdb53fc78140878dc0d6dccdd352bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":418,
              "y":99},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d861ee3c73674f03bbb783b77f242ada",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":418,
                  "y":99},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd3d2ef0131f4d9bb8646003d9776df5",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":418,
              "y":125},
            "size":{
              "width":113,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70392fc6189e40a8a734e49a21422d97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":418,
                  "y":125},
                "size":{
                  "width":113,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"abcb8af0c6ad4fb2a0eaf44994dae934",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":418,
              "y":151},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f63c58124324c0c8689cf4f6d11b17a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":418,
                  "y":151},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"016beec79a6a40b8b6361ab532065643",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":240},
            "size":{
              "width":532,
              "height":310}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a286c1ffd9b4fa5aa142fcee3d8385e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":240},
                "size":{
                  "width":532,
                  "height":310}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/task_1/u34.png"}},
{
          "id":"78fcc1b973b445269b56b88b5815c0fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":252,
              "y":250},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c54bc09429dd4707ae86edcb7219b77e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":252,
                  "y":250},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0ae36f18213484686249316d3db19d1",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":301},
            "size":{
              "width":113,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bebbbd334d2c4ec7b7e6d56a9cefbc24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":301},
                "size":{
                  "width":113,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4317dbf3fe884c3dae22e215a5bcef32",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":364},
            "size":{
              "width":149,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da8b0a33af8b4033a4ab679b57d231ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":364},
                "size":{
                  "width":149,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"be6029cdec6144a9b1a180078981df96",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":496},
            "size":{
              "width":219,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46484ff4af554d5bbdc5346fc132865d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":496},
                "size":{
                  "width":219,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c0debea7450944beb8d0788237ba4e39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":342,
              "y":348},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f72df4c9f8047dfad51ea74f978d467",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":342,
                  "y":348},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c8aa3a6eeb1461d81fe22f2e84d3dd7",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":466,
              "y":341},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0c7f599b9274c3391d9830246e9266b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":466,
                  "y":341},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"1a7b0b0cdae1453c8c5b4be8f8bfe9f5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":412,
              "y":345},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6cb05ed8022846f5b72b3b12f8a1c543",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":466,
              "y":357},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6378609859f2433db4de96544a466e2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":466,
                  "y":357},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6cf3fc6808fd40da94275a04925dadd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":342,
              "y":522},
            "size":{
              "width":109,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"624d2aebdcf7446e95b1a65f68b62bcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":342,
                  "y":522},
                "size":{
                  "width":109,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc00ee38db6748179877dcf41958be7f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":517},
            "size":{
              "width":77,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"273bf9964f7143ce9c9d926b4a340225",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":570},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a9f4d6c26c56429aaac7767009078416",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":570},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"34179175e9d74d29b53cf5308c2ec0f7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":570},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f765bb430ad0444abd319ce142a7b29c",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":415,
              "y":177},
            "size":{
              "width":116,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e71f324a708343dd8ec099c23d991a63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":415,
                  "y":177},
                "size":{
                  "width":116,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"ce8d2af84079405e989430f57ec2f7a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":342,
              "y":386},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f9b16c0aadc49a9931cb2fd433ffa15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":342,
                  "y":386},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b878127c50bc4f90ae769441c24e099f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":412,
              "y":383},
            "size":{
              "width":129,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"ca1c604d638d4868b76d8d64a9e3ad7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":208},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29a9c21b192543939641961e7f968c0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":208},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ba3b276c0574589a7008d8791228f2b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":205},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c3013b6623b9421b88638f99c61b7b43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":342,
              "y":299},
            "size":{
              "width":109,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b55317c776341f2bc65f90386646146",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":342,
                  "y":299},
                "size":{
                  "width":109,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8210658f4a5a4344b472420666baa40c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":295},
            "size":{
              "width":77,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ae8ad4f8f3794a32ab564d9cbb5f646e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":330},
            "size":{
              "width":532,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/task_1/u68_line.png"}},
{
          "id":"7c0d1536e95e42d7a4e5fd5ce85bf85e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":455},
            "size":{
              "width":532,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/task_1/u68_line.png"}},
{
          "id":"d7f97610526d4af4b09c7df0ee1fa7ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":342,
              "y":420},
            "size":{
              "width":109,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76c893c28b1a4dca85f802a9744a4f0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":342,
                  "y":420},
                "size":{
                  "width":109,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7fde314f82b45398c7dca84104d245e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":415},
            "size":{
              "width":77,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f85b7167c38446598aac805d843ee67b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":342,
              "y":484},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a13f67176d647139dbd2be7f0d4c08c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":342,
                  "y":484},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdc31a1247874e9d8dd12e861af7f6b9",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":457,
              "y":475},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a790e8daa2204ab7b91c29908996c937",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":457,
                  "y":475},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c05a07d3df5c4deeb5545062364d17a1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":412,
              "y":479.5},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1e6815d9d70c4e19a0e3cdaaa62deb9f",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":457,
              "y":491},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52a350cc86614584929d39dc7da3f321",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":457,
                  "y":491},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "614f077af181494a913dda5407de8b37":{
      "packageId":"614f077af181494a913dda5407de8b37",
      "type":"Axure:Master",
      "name":"Page Template",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"605db743b3284059a9ccb5dd9fe3f62c",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
              "size":{
                "width":980,
                "height":120}},
            "adaptiveStyles":{
},
            "masterId":"cd9e0e7c2c1d475fb5556f5167e2eed2"},
{
            "id":"d2177a92348a4933be6325fcc3cd564e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":81},
              "size":{
                "width":1390,
                "height":1109},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2c287c13165a4bf0b082aba0b4ddfe6e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":81},
                  "size":{
                    "width":1390,
                    "height":1109},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/task/u22.png"}}]}},
    "cd9e0e7c2c1d475fb5556f5167e2eed2":{
      "packageId":"cd9e0e7c2c1d475fb5556f5167e2eed2",
      "type":"Axure:Master",
      "name":"Navigation - Header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"81c938b822334285a9888f8e12d462da",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Franklin Gothic Book Regular', 'Franklin Gothic Book'",
              "horizontalAlignment":"right",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0033CC,
                "opacity":1},
              "location":{
                "x":944,
                "y":0},
              "size":{
                "width":50,
                "height":17},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3f8dc09a6ebe4a3e94cbd650909c964b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Franklin Gothic Book Regular', 'Franklin Gothic Book'",
                  "horizontalAlignment":"right",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0033CC,
                    "opacity":1},
                  "location":{
                    "x":944,
                    "y":0},
                  "size":{
                    "width":50,
                    "height":17},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"87621b3e11214264ac8e4feedbf2ceee",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":934,
                "y":0},
              "size":{
                "width":10,
                "height":15},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFF3333}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/task/u11_line.png"}},
{
            "id":"9f2052e025df46b0a6e32a0ad3024415",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Franklin Gothic Book Regular', 'Franklin Gothic Book'",
              "horizontalAlignment":"right",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0033CC,
                "opacity":1},
              "location":{
                "x":894,
                "y":0},
              "size":{
                "width":35,
                "height":17},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ecc9a55b9b8342f1a0b1b6b1a9638ffc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Franklin Gothic Book Regular', 'Franklin Gothic Book'",
                  "horizontalAlignment":"right",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0033CC,
                    "opacity":1},
                  "location":{
                    "x":894,
                    "y":0},
                  "size":{
                    "width":35,
                    "height":17},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2e7eaee0d5fc4ca8a2cc1a8af37b812e",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":889,
                "y":0},
              "size":{
                "width":10,
                "height":15},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFF3333}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/task/u11_line.png"}},
{
            "id":"cb12707ea13c42e7b266147bd4f92ab8",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Franklin Gothic Book Regular', 'Franklin Gothic Book'",
              "horizontalAlignment":"right",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0033CC,
                "opacity":1},
              "location":{
                "x":835,
                "y":0},
              "size":{
                "width":49,
                "height":17},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e902292eb0c84de98c476c22e90b8c50",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Franklin Gothic Book Regular', 'Franklin Gothic Book'",
                  "horizontalAlignment":"right",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0033CC,
                    "opacity":1},
                  "location":{
                    "x":835,
                    "y":0},
                  "size":{
                    "width":49,
                    "height":17},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ede20f2200254268a0e62955bb4c427c",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":820,
                "y":0},
              "size":{
                "width":10,
                "height":15},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFF3333}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/task/u11_line.png"}},
{
            "id":"e54cfe20288e4131a1cebf1a78dab487",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Franklin Gothic Book Regular', 'Franklin Gothic Book'",
              "horizontalAlignment":"right",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0033CC,
                "opacity":1},
              "location":{
                "x":650,
                "y":0},
              "size":{
                "width":165,
                "height":17},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68986a5045e943739e1aebd7add46451",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Franklin Gothic Book Regular', 'Franklin Gothic Book'",
                  "horizontalAlignment":"right",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0033CC,
                    "opacity":1},
                  "location":{
                    "x":650,
                    "y":0},
                  "size":{
                    "width":165,
                    "height":17},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"79aa9213b4aa4c27bfbee9df4772957b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Neutraface Slab Text Regular', 'Neutraface Slab Text'",
              "horizontalAlignment":"left",
              "verticalAlignment":"bottom",
              "paddingTop":"0",
              "paddingBottom":"0",
              "location":{
                "x":0,
                "y":15},
              "size":{
                "width":210,
                "height":65},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"82267db647294f509021621e91f8b622",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Neutraface Slab Text Regular', 'Neutraface Slab Text'",
                  "horizontalAlignment":"left",
                  "verticalAlignment":"bottom",
                  "paddingTop":"0",
                  "paddingBottom":"0",
                  "location":{
                    "x":0,
                    "y":15},
                  "size":{
                    "width":210,
                    "height":65},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/financial_app_sample/u16.jpg"}}]}}},
  "objectPaths":{
    "bc187aae2b104b498d0c473cc96c85c6":{
      "scriptId":"u0",
      "605db743b3284059a9ccb5dd9fe3f62c":{
        "scriptId":"u1",
        "81c938b822334285a9888f8e12d462da":{
          "scriptId":"u2"},
        "3f8dc09a6ebe4a3e94cbd650909c964b":{
          "scriptId":"u3"},
        "87621b3e11214264ac8e4feedbf2ceee":{
          "scriptId":"u4"},
        "9f2052e025df46b0a6e32a0ad3024415":{
          "scriptId":"u5"},
        "ecc9a55b9b8342f1a0b1b6b1a9638ffc":{
          "scriptId":"u6"},
        "2e7eaee0d5fc4ca8a2cc1a8af37b812e":{
          "scriptId":"u7"},
        "cb12707ea13c42e7b266147bd4f92ab8":{
          "scriptId":"u8"},
        "e902292eb0c84de98c476c22e90b8c50":{
          "scriptId":"u9"},
        "ede20f2200254268a0e62955bb4c427c":{
          "scriptId":"u10"},
        "e54cfe20288e4131a1cebf1a78dab487":{
          "scriptId":"u11"},
        "68986a5045e943739e1aebd7add46451":{
          "scriptId":"u12"},
        "79aa9213b4aa4c27bfbee9df4772957b":{
          "scriptId":"u13"},
        "82267db647294f509021621e91f8b622":{
          "scriptId":"u14"}},
      "d2177a92348a4933be6325fcc3cd564e":{
        "scriptId":"u15"},
      "2c287c13165a4bf0b082aba0b4ddfe6e":{
        "scriptId":"u16"}},
    "f166583c2c20436987b0cc4b33e8875f":{
      "scriptId":"u17"},
    "9c183bd4271a48dbb376a715ec557a6e":{
      "scriptId":"u18"},
    "67e4d6cd63fc4b229bdfd5de6db9771f":{
      "scriptId":"u19"},
    "da186554ecef4ea2a90d0720d2789d3b":{
      "scriptId":"u20"},
    "b2f51e3e8c4e42a881ac38621b838691":{
      "scriptId":"u21"},
    "1cd98109a0f648bd8daa27f147d51b99":{
      "scriptId":"u22"},
    "1d5ce1f717f245c0ac1fdeecdfa7835e":{
      "scriptId":"u23"},
    "0798e04d543c492e8b7fbc00be01e3db":{
      "scriptId":"u24"},
    "83a89eb7a6224c8c9c52fcd8bb2f865c":{
      "scriptId":"u25"},
    "548568981fc44d3a95ec0e75adb8c475":{
      "scriptId":"u26"},
    "fabacb0a7a34488695312318534a1a4a":{
      "scriptId":"u27"},
    "2bbdb53fc78140878dc0d6dccdd352bc":{
      "scriptId":"u28"},
    "d861ee3c73674f03bbb783b77f242ada":{
      "scriptId":"u29"},
    "fd3d2ef0131f4d9bb8646003d9776df5":{
      "scriptId":"u30"},
    "70392fc6189e40a8a734e49a21422d97":{
      "scriptId":"u31"},
    "abcb8af0c6ad4fb2a0eaf44994dae934":{
      "scriptId":"u32"},
    "0f63c58124324c0c8689cf4f6d11b17a":{
      "scriptId":"u33"},
    "016beec79a6a40b8b6361ab532065643":{
      "scriptId":"u34"},
    "1a286c1ffd9b4fa5aa142fcee3d8385e":{
      "scriptId":"u35"},
    "78fcc1b973b445269b56b88b5815c0fd":{
      "scriptId":"u36"},
    "c54bc09429dd4707ae86edcb7219b77e":{
      "scriptId":"u37"},
    "a0ae36f18213484686249316d3db19d1":{
      "scriptId":"u38"},
    "bebbbd334d2c4ec7b7e6d56a9cefbc24":{
      "scriptId":"u39"},
    "4317dbf3fe884c3dae22e215a5bcef32":{
      "scriptId":"u40"},
    "da8b0a33af8b4033a4ab679b57d231ab":{
      "scriptId":"u41"},
    "be6029cdec6144a9b1a180078981df96":{
      "scriptId":"u42"},
    "46484ff4af554d5bbdc5346fc132865d":{
      "scriptId":"u43"},
    "c0debea7450944beb8d0788237ba4e39":{
      "scriptId":"u44"},
    "8f72df4c9f8047dfad51ea74f978d467":{
      "scriptId":"u45"},
    "1c8aa3a6eeb1461d81fe22f2e84d3dd7":{
      "scriptId":"u46"},
    "c0c7f599b9274c3391d9830246e9266b":{
      "scriptId":"u47"},
    "1a7b0b0cdae1453c8c5b4be8f8bfe9f5":{
      "scriptId":"u48"},
    "6cb05ed8022846f5b72b3b12f8a1c543":{
      "scriptId":"u49"},
    "6378609859f2433db4de96544a466e2e":{
      "scriptId":"u50"},
    "6cf3fc6808fd40da94275a04925dadd9":{
      "scriptId":"u51"},
    "624d2aebdcf7446e95b1a65f68b62bcc":{
      "scriptId":"u52"},
    "bc00ee38db6748179877dcf41958be7f":{
      "scriptId":"u53"},
    "273bf9964f7143ce9c9d926b4a340225":{
      "scriptId":"u54"},
    "a9f4d6c26c56429aaac7767009078416":{
      "scriptId":"u55"},
    "34179175e9d74d29b53cf5308c2ec0f7":{
      "scriptId":"u56"},
    "f765bb430ad0444abd319ce142a7b29c":{
      "scriptId":"u57"},
    "e71f324a708343dd8ec099c23d991a63":{
      "scriptId":"u58"},
    "ce8d2af84079405e989430f57ec2f7a8":{
      "scriptId":"u59"},
    "4f9b16c0aadc49a9931cb2fd433ffa15":{
      "scriptId":"u60"},
    "b878127c50bc4f90ae769441c24e099f":{
      "scriptId":"u61"},
    "ca1c604d638d4868b76d8d64a9e3ad7f":{
      "scriptId":"u62"},
    "29a9c21b192543939641961e7f968c0b":{
      "scriptId":"u63"},
    "4ba3b276c0574589a7008d8791228f2b":{
      "scriptId":"u64"},
    "c3013b6623b9421b88638f99c61b7b43":{
      "scriptId":"u65"},
    "2b55317c776341f2bc65f90386646146":{
      "scriptId":"u66"},
    "8210658f4a5a4344b472420666baa40c":{
      "scriptId":"u67"},
    "ae8ad4f8f3794a32ab564d9cbb5f646e":{
      "scriptId":"u68"},
    "7c0d1536e95e42d7a4e5fd5ce85bf85e":{
      "scriptId":"u69"},
    "d7f97610526d4af4b09c7df0ee1fa7ae":{
      "scriptId":"u70"},
    "76c893c28b1a4dca85f802a9744a4f0a":{
      "scriptId":"u71"},
    "a7fde314f82b45398c7dca84104d245e":{
      "scriptId":"u72"},
    "f85b7167c38446598aac805d843ee67b":{
      "scriptId":"u73"},
    "9a13f67176d647139dbd2be7f0d4c08c":{
      "scriptId":"u74"},
    "fdc31a1247874e9d8dd12e861af7f6b9":{
      "scriptId":"u75"},
    "a790e8daa2204ab7b91c29908996c937":{
      "scriptId":"u76"},
    "c05a07d3df5c4deeb5545062364d17a1":{
      "scriptId":"u77"},
    "1e6815d9d70c4e19a0e3cdaaa62deb9f":{
      "scriptId":"u78"},
    "52a350cc86614584929d39dc7da3f321":{
      "scriptId":"u79"}}});