{
    'name': 'Report Layout',
    'category': 'Reprot',
    'summary': 'Add custom header and footer',
    'author': 'Genweb2',
    'website': 'genweb2.com',
    'depends': ['web','report'],
    'data': [
        'data/paperformat.xml',
        'views/inherite_layout.xml',
        'views/templates.xml',
        'views/gbs_internal_layout.xml',
        'views/gbs_external_layout.xml',
        'views/external_layout_address.xml',
        'views/gbs_custom_pad_report_template.xml',
        'views/gbs_custom_pad_report_with_system_sig_template.xml',
        'views/gbs_po_layout.xml',
    ],
    'installable': True,
    'auto_install': True,
    'application': True,
}
