{
    'name': "Employee Orientation & Training",
    "version": "1.1.0",
    "category": "gbs Modules/Human Resources",
    'summary': """Employee Orientation/Training Program""",
    'description': """Complete Employee Orientation/Training Program""",
    "author": "Genweb2 Limited",
    "website": "http://www.genweb2.com",
    'depends': ['base', 'hr', 'mail', ],
    'data': [
        'views/orientation_checklist_line.xml',
        'views/orientation_checklist.xml',
        'views/employee_orientation.xml',
        'views/orientation_checklists_request.xml',
        'views/orientation_checklist_sequence.xml',
        #'views/orientation_request_mail_template.xml',
        'views/employee_training.xml',
        'security/ir.model.access.csv',
    ],
    'images': ['static/description/banner.jpg'],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
