{
    'name': 'GBS Samuda Sales Installation',
    'version': '10.0.1.0.0',
    'author': 'Genweb2 Limited',
    'website': 'http://www.genweb2.com',
    'category': 'Sales',
    'depends': [
        'gbs_sales_commission',
        'customer_credit_limit',
        'gbs_sales_commission_so',
        'gbs_sale_delivery_settings',
        'gbs_product',
        'product_sales_pricelist',
        'delivery_order',
        'gbs_sale_order_approval',
        'sale_order_type',
        'sale_order_revision',
        'samuda_so_type',
        'gbs_pi_creation',
        'delivery_schedules',
        'gbs_application_group',
        'delivery_invoicing',
        'accounting_report',
        'gbs_accounting_cheque_received',
        'delivery_qty_reports',
        'sale_operating_unit',
        'lc_sales_product_local',
        'lc_sales_local_report',
        'delivery_challan_report',
        'inventory_dashboad_inherit',
        'gbs_application_security',
        'stock_warehouse_extend',
        'stock_move_backdating',
        'board',
        'web_access_rule_button_extend',
        'delivery_jar_counting',
        # 'customer_area',
        'terms_setup',
        'gbs_sales_commission_invoice',
        'gbs_sales_commission_account',
        'gbs_samuda_sales_approval_menu',
        'gbs_customize_accountant',
        'gbs_samuda_stock',
        'gbs_account_receivable_auto_set',
        'samuda_sales_country',
        'gbs_payment_term',
        'gbs_res_partner',
        'gbs_account_invoice_report',
    ],
    'data': [],
    'description': 'Install all modules which is related with sales',
    'installable': True,
    'application': False,
}
