# -*- coding: utf-8 -*-

{
    'name': 'HR Installation',
    'author': 'Genweb2 Limited',
    'website': 'www.genweb2.com',
    'category': 'Module Installation',
    'summary': 'Install all HR related module',
    'description': 'Install all HR related module',
    'version': '1.0',
    'depends': [
        'emk_hr',
        'gbs_hr_payroll',
        # 'gbs_hr_payroll_bank_letter',
        # 'gbs_hr_payroll_top_sheet',
        'gbs_hr_attendance_report',
        'gbs_hr_leave_report',
        'hr_attendance_and_ot_summary',
        'hr_attendance_dashboard',
        'hr_manual_attendance',
        'hr_employee_attendance_payroll',
        'hr_employee_mobile_bills_payroll',
        'hr_employee_meal_bills_payroll',
        'hr_other_allowance_payroll',
        'hr_other_allowance_payroll',
        'hr_payroll_arrear',
        'hr_earned_leave',
        'hr_recruitment_survey',
        'gbs_base_package',
        'gbs_hr_package',
        'hr_holiday_utility',
        'hr_holidays_multi_approval_notification',
        'base_suspend_security',
        'base_bank_bd',
        'gbs_hr_employee_security',
        'ir_sequence_operating_unit',
        'gbs_hr_public_holidays',
        'gbs_hr_leave_duration_correction',
        'gbs_hr_security',
        'hr_family',
        'hr_contract_reference',
        'hr_employee_iou_payroll',
        'hr_employee_number',
        'hr_employee_exit',
        'hr_short_leave',
        'hr_employee_number',
        'website_hr_recruitment',
        'hr_holidays_compute_days',
        'hr_absence_summary',
        "hr_short_leave",
        "hr_holidays",
        "account",
        "gbs_hr_leave_duration_correction",
        "gbs_hr_public_holidays",
        "hr_holiday_exception",
        "account_accountant",
        "hr_payroll",
        "birth_day_notification",
        "gbs_hr_holiday_hour",
        "hr",
        "hr_attendance",
        "hr_recruitment",
        "gbs_hr_department_sequence",
        "account_bank_statement_import",
        "document",
        "emk_hr",
        "emk_payment",
        "employee_stages",
        "gbs_application_group",
        "gbs_base_package",
        "gbs_data_migration",
        "gbs_hr_attendance",
        "gbs_hr_attendance_error_correction",
        "gbs_hr_attendance_grace_time",
        "gbs_hr_attendance_report",
        "gbs_hr_attendance_utility",
        "gbs_hr_device_config",
        "gbs_hr_employee",
        "gbs_hr_employee_documents",
        "gbs_hr_employee_security",
        "gbs_hr_leave_report",
        "gbs_hr_package",
        "gbs_hr_payroll",
        "gbs_hr_security",
        "hr_attendance_and_ot_summary",
        "hr_attendance_dashboard",
        "hr_attendance_import",
        "hr_contract",
        "hr_contract_reference",
        "hr_earned_leave",
        "hr_employee_attendance_payroll",
        "hr_employee_exit",
        "hr_employee_iou",
        "hr_employee_iou_payroll",
        "hr_employee_loan",
        "hr_employee_loan_payroll",
        "hr_employee_meal_bills",
        "hr_employee_meal_bills_payroll",
        "hr_employee_mobile_bills",
        "hr_employee_mobile_bills_payroll",
        "hr_employee_number",
        "hr_employee_seniority",
        "hr_experience",
        "hr_family",
        "hr_holiday_utility",
        "hr_holiday_year",
        "hr_holidays_multi_approval_notification",
        "hr_holidays_multi_levels_approval",
        "hr_manual_attendance",
        "hr_other_allowance",
        "hr_other_allowance_payroll",
        "hr_overtime_requisition",
        "hr_payroll_arrear",
        "hr_payroll_festival_bonus",
        "hr_recruitment_survey",
        "hr_rostering",
        "l10n_generic_coa",
        "l10n_in_hr_payroll",
        "hr_attendance_settings",
        "hr_employee_operating_unit",
        "gbs_hr_recruitment",

    ],
    'installable': True,
    'application': True,
}
