# -*- coding: utf-8 -*-

{
    'name': 'Cafeteria Installation',
    'author': 'Genweb2 Limited',
    'website': 'www.genweb2.com',
    'category': 'Cafeteria Installation',
    'category': 'Module Installation',
    'summary': 'Install all cafeteria related module',
    'description': 'Install all cafeteria related module',
    'version': '1.0',
    'depends': [
        'point_of_sale',
        'pos_reprint',
        'pos_discount',
        'product_sequence',
        # 'web_printscreen_zb',
        # 'pos_notes',
        # 'pos_operating_unit',
        # 'web_branding',
        # 'pos_discount_total',
        # 'opa_advance_date_search',
        # 'extend_product_sequence',
        # 'pos_access',
        # 'product_extend',
        # 'customer_extend',
        # 'ineherit_point_of_sale',
        # 'reprint_pos_report',
        # 'category_stock_summary_reports',
        # 'pebbles_invoice_analysis',
        # 'pos_summary_report',
        # 'pos_gift_ticket',
        # 'product_barcode_qweb',
        # 'web_hide_db_manager_link',
        # 'pebbles_invoice_analysis',
    ],
    'installable': True,
    'application': True,
}
