import analytic_account_wizard
import inherit_picking_import_wizard
import picking_import_wizard
import journal_entry_post_wizard
import update_rate_wizard
import success_wizard
import landed_cost_report_wizard
