{
    'name': 'Customer Report',
    'category': 'Reprot',
    'summary': 'Add custom header and footer',
    'author': 'Md. Mehedi Hasan',
    'website': 'https://github.com/gitmehedi',
    'depends': ['web','report'],
    'data': [
        'data/paperformat.xml',
        'views/inherite_layout.xml',
        'views/templates.xml',
        'views/gbs_internal_layout.xml',
        'views/gbs_external_layout.xml',
        'views/external_layout_address.xml',
        'views/gbs_custom_pad_report_template.xml',
        'views/gbs_custom_pad_report_with_system_sig_template.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
