{
    "name": 'Product Requisition',
    "summary": "Product Requisition",
    "category": "Purchase",
    "depends": [
        'base',
        'purchase',
        'stock',
        'operating_unit',
        'stock_operating_unit'
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/ir.rule.xml",
        "views/menu.xml",
        "wizards/product_usage_summary_wizard_views.xml",
        "wizards/all_branch_requisition_wizard_views.xml",
        "wizards/product_requisition_template_wizard_views.xml",
        "wizards/branch_selection_wizard_views.xml",
        "views/branch_issue_views.xml",
        "views/branch_receive_views.xml",
        "views/extend_operating_unit_views.xml",
        "views/product_usage_history_views.xml",
        "views/product_requisition_template_views.xml",
        "views/product_requisition_views.xml",
        "views/purchase_requisition_views.xml",
        "reports/product_usage_summary_report_views.xml",
        "reports/all_branch_requistion_report_views.xml",
        "reports/product_usage_history_analysis_report_views.xml",
        "reports/product_requisition_report.xml",
    ],
    "installable": True,
    "application": True,
}
