from . import branch
from . import inherited_res_users
from . import inherited_stock_move
from . import inherited_stock_picking
from . import inherited_account_invoice
from . import inherited_account_payment
from . import inherited_stock_warehouse
from . import inherited_stock_location
from . import inherited_account_bank_statement
from . import inherited_account_bank_statement_line
from . import inherited_stock_inventory
from . import inherited_customer
from . import inherited_product
from . import inherited_res_company
