import sale_price_change
import product_sale_price_history_line
import inherit_product_template
import product_packaging_mode
import inherit_res_partner
import inherited_product_product
import inherited_ir_attachment
