from . import customer_aging_statement_wizard
from . import executive_sales_wizard
from . import customer_sales_wizard
from . import customer_sales_sector_wizard
from . import sector_sales_product_wizard
from . import outstanding_statement_wizard
from . import credit_details_product_wizard
from . import yearly_sales_comparison_wizard
from . import daily_delivery_statement_wizard
from . import daily_undelivered_statement_wizard
from . import monthly_delivery_executive_wizard
from . import monthly_delivery_product_wizard
