# -*- coding: utf-8 -*-

{
    'name': 'Event Installation',
    'author': 'Genweb2 Limited',
    'website': 'www.genweb2.com',
    'category': 'Module Installation',
    'summary': 'Install all event related module',
    'description': 'Install all event related module',
    'version': '1.0',
    'depends': [
        'event',
        'website_event',
        # 'event_barcode',
        'product',
        'account',
        'report_layout',
        'mail_send',
        'event_user',
        'website_event_filter_selector',
        'event_user',
        'event_management',
        'event_registration',
        'event_sessions',
        'emk_payment',
        'create_partner_user',
        "emk_menu",
        "emk_payment",
        "employee_stages",
        "event",
        "event_mail",
        "event_management",
        "event_payment",
        "event_sessions",
        "event_user",
    ],
    'installable': True,
    'application': True,
}
