# -*- coding: utf-8 -*-

{
    'name': 'Pebbles Installation Module',
    'author': 'Genweb2 Limited',
    'website': 'www.genweb2.com',
    'category': 'Pebbles Installation',
    'data': [
    ],
    'depends': ['sale',
                'purchase',
                'stock',
                'point_of_sale',
                'pos_loyalty',
                'pos_promotion_loyalty',
                'product_variant_matrix',
                'stock_distribution_matrix',
                'product_category_extend',
                'web_widget_distribution_matrix',
                'web_widget_goods_recevie_matrix',
                'product_category_extend',
                'pos_promotion',
                'web_widget_x2many_2d_checkbox',
                'web_widget_x2many_2d_matrix',
                'web_widget_x2many_2d_opening_matrix',
                'purchase_order_pebbles'],
    'category': 'Installation Module',
    'summary': 'Install Pebbles Module',
    'description': 'Install Pebbles Module',
    'installable': True,
    'application': True,
}
