# -*- coding: utf-8 -*-

{
    'name': 'Pebbles Installation Module',
    'author': 'Genweb2 Limited',
    'website': 'www.genweb2.com',
    'category': 'Pebbles Installation',
    'version': '1.0.0',
    'data': [],
    'depends': ['sale',
                'purchase',
                'stock',
                'stock_distribution_matrix',
                'product_extend',
                'product_category_extend',
                'web_widget_distribution_matrix',
                'web_widget_goods_recevie_matrix',
                'web_widget_x2many_2d_checkbox',
                'web_widget_x2many_2d_matrix',
                'web_widget_x2many_2d_opening_matrix',
                'purchase_order_pebbles',
                'product_variant_matrix',
                'product_brand',
                'pebbles_invoice_analysis',
                'stock_requisition_transfer',
                'stock_transfer_request',
                'stock_summary_report',
                'operating_unit',
                'pos_operating_unit',
                ],
    'category': 'Installation Module',
    'summary': 'Install Pebbles Module',
    'description': 'Install Pebbles Module',
    'installable': True,
    'application': True,
    'auto_install': False,
}
