from . import segment
from . import acquiring_channel
from . import servicing_channel
from . import inherit_res_currency
from . import branch
from . import inherit_account_journal
from . import inherit_res_bank
from . import inherit_account_move
from . import inherit_account_account
from . import inherit_account_type
from . import inherit_product_product
from . import account_analytic_account
from . import inherit_res_partner_bank
