from . import segment
from . import acquiring_channel
from . import servicing_channel
from . import inherit_res_currency
from . import branch
from . import inherit_account_tax
from . import inherit_account_journal
from . import inherit_res_bank
from . import inherit_account_move
from . import inherit_account_account
from . import inherit_account_type
from . import inherit_product_product
from . import account_analytic_account
from . import inherit_res_partner_bank
from . import inherit_res_currency_rate
from . import inherit_vendor_advance
from . import account_invoice
from . import inherit_vendor_security_return
from . import inherit_res_partner
from . import inherit_account_config
from . import inherit_vendor_security_deposit
from . import date_range_type
from . import date_range
from . import inherit_tds_vat_payment
from . import receive_outstanding_advance
from . import inherit_tds_vat_chalan
