$axure.loadCurrentPage({
  "url":"task.html",
  "generationDate":new Date(1462978068951.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NotesSA"],
  "page":{
    "packageId":"2b0f8dde12af4b67a6b4c5eeb57394b1",
    "type":"Axure:Page",
    "name":"Task",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b028ab61ab63406cadd81f09de422ca1",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":780}},
          "adaptiveStyles":{
},
          "masterId":"9447b50b9fcc46369087c32d45b2eb92"},
{
          "id":"15880db42c004553a88490d8e863e8e4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"614f077af181494a913dda5407de8b37"},
{
          "id":"cae31c4f3f9a489e9d23a55b2aa13905",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":151},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69cc2d442f7b4d669cb50029b31fece2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":151},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa4b9b62846a40efbf50db7643b5ad56",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":191,
              "y":147},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b76dcd1b20ba481bb36c7dfb7e2ff458",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":187},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0fe908ca2234f3cbc549932c17c8c66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":187},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1c59a7c7c974be7bf98a9551e3f538d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":191,
              "y":183},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"b04968727065451d96f5e3b07d1aefb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":219},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"144c1bbc41684d46a7367a5be599aa04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":219},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b3f3e30ee954a6da750d7007c17e92b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":191,
              "y":215},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"8cab25fee0c54bb6815b48c36e5b7353",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":417,
              "y":185},
            "size":{
              "width":150,
              "height":65},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCE8F1},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdef5756f6d04f7ab2b0ed5e9c9efc2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":417,
                  "y":185},
                "size":{
                  "width":150,
                  "height":65},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCE8F1},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/task/u33.png"}},
{
          "id":"8fe1f06653284a77b5ba30d9be2956ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF31708F,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFD9EDF7},
{
                  "color":0xFFD9EDF7},
{
                  "color":0xFFC4E3F3},
{
                  "color":0xFFC4E3F3}]},
            "location":{
              "x":417,
              "y":147},
            "size":{
              "width":150,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCE8F1},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ebf4989ca3644bcbde26fd9789e3afd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF31708F,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFD9EDF7},
{
                      "color":0xFFD9EDF7},
{
                      "color":0xFFC4E3F3},
{
                      "color":0xFFC4E3F3}]},
                "location":{
                  "x":417,
                  "y":147},
                "size":{
                  "width":150,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCE8F1},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/task/u35.png"}},
{
          "id":"93ff4253be534b03bbc4af5499e6c7b5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":417,
              "y":179},
            "size":{
              "width":150,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCE8F1}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/task/u37_line.png"}},
{
          "id":"c3527ca89326446aae2395242cca8a32",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":189},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f8b0d0cf4944c3fbbbb801c50277c55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":189},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"52f253b79fd14675851bcdda2ae97ed8",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":207},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e42ec42f062540f49098654b718d9b28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":207},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b2e6836015444582b21f99f8ac8f95eb",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":226},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40a5b160d4bf48b88147515eb20cde77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":226},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"59f6b77b42c34d38a98df44346323ba0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":587,
              "y":184},
            "size":{
              "width":150,
              "height":65},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCE8F1},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"796fbdf68af946ed805e44a6c0443e8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":587,
                  "y":184},
                "size":{
                  "width":150,
                  "height":65},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCE8F1},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/task/u33.png"}},
{
          "id":"e39df351a70547dfad628ab6ab6253a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF31708F,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFD9EDF7},
{
                  "color":0xFFD9EDF7},
{
                  "color":0xFFC4E3F3},
{
                  "color":0xFFC4E3F3}]},
            "location":{
              "x":587,
              "y":146},
            "size":{
              "width":150,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCE8F1},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"207a950a8aff484fa4d3b841dc55d935",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF31708F,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFD9EDF7},
{
                      "color":0xFFD9EDF7},
{
                      "color":0xFFC4E3F3},
{
                      "color":0xFFC4E3F3}]},
                "location":{
                  "x":587,
                  "y":146},
                "size":{
                  "width":150,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCE8F1},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/task/u35.png"}},
{
          "id":"c311d78971c0464d8166c2c413349c62",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":587,
              "y":178},
            "size":{
              "width":150,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCE8F1}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/task/u37_line.png"}},
{
          "id":"1df7e41a24e142edb11e2e006071f21d",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":194},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"087a83edbb894cd89e6d849c4008320e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":194},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"7afc47f3bbc3411f946e61c884a47d04",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":212},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e6765e627924027a2f89801b1b00072",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":212},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"e830202f19dd4e6d8d699f89a5cb5fa2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":757,
              "y":185},
            "size":{
              "width":220,
              "height":65},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCE8F1},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec9df1d67acc427e8ef999ed12541343",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":757,
                  "y":185},
                "size":{
                  "width":220,
                  "height":65},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCE8F1},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/task/u53.png"}},
{
          "id":"3f04f63984e04f0494e11806ae0670c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF31708F,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFD9EDF7},
{
                  "color":0xFFD9EDF7},
{
                  "color":0xFFC4E3F3},
{
                  "color":0xFFC4E3F3}]},
            "location":{
              "x":757,
              "y":147},
            "size":{
              "width":220,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCE8F1},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdefa150f1fc4cdca3acafd5b85383ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF31708F,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFD9EDF7},
{
                      "color":0xFFD9EDF7},
{
                      "color":0xFFC4E3F3},
{
                      "color":0xFFC4E3F3}]},
                "location":{
                  "x":757,
                  "y":147},
                "size":{
                  "width":220,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCE8F1},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/task/u55.png"}},
{
          "id":"f09f1508fe1a425f96d2da06522d987f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":757,
              "y":179},
            "size":{
              "width":150,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCE8F1}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/task/u37_line.png"}},
{
          "id":"d07dd707b1014df5b1af15cb6a8a76fb",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":765,
              "y":191},
            "size":{
              "width":142,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf008d9b7dec4c89a210136ef14de73e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":765,
                  "y":191},
                "size":{
                  "width":142,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"d0987333a6ca44ce87eba44b6f4bee8d",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":765,
              "y":209},
            "size":{
              "width":155,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e2ec0954d8644d9bafc18cfb86c1684",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":765,
                  "y":209},
                "size":{
                  "width":155,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"283a266e01404483a23b75805712a561",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":765,
              "y":226},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1815089b6f37437a944fb46a688f89b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":765,
                  "y":226},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0f907b34723c4ddcb972dbd49518180b",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":191,
              "y":245},
            "size":{
              "width":18,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23ea19e717444f6f955efd85be69b8cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":191,
                  "y":245},
                "size":{
                  "width":18,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"7b2e3ae8a34340c1aad8a2193cd40dca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":277},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00b7942340af4ae0a615c6eb7c426ab1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":277},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"067075349c314d059e5629a13b04e9e7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":191,
              "y":272.5},
            "size":{
              "width":89,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"aa4e52a24acb422f8fdbf03da12449b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":245},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10e5a16f8a3c4f819a8fcb1ea2e04c49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":245},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72bc9c4fddce4b7fb09a540dc398b9a0",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":268.5},
            "size":{
              "width":91,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36857b1e92584183a1cdf7a0c092d4d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":268.5},
                "size":{
                  "width":91,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"3b22dd93583b4de9b349bcc0ea4bc0ed",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":285.5},
            "size":{
              "width":91,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83cc23c470224eb0a3a30fb911fc204c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":285.5},
                "size":{
                  "width":91,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4733add2122842df93a3e3d95c6f0c6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":312},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdb951f56fce44f9929893d56aeb4b40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":312},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75a21926458145e98aadcf675a3e8a05",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":192,
              "y":308},
            "size":{
              "width":89,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e99aeb01288540dea91e0b1c8c8b1527",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"24px",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF2D6CA2},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF285E8E}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF2D6CA2},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF2B669A}}},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF428BCA},
{
                  "color":0xFF428BCA},
{
                  "color":0xFF2D6CA2},
{
                  "color":0xFF2D6CA2}]},
            "textShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":-1,
              "blurRadius":0,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.2}},
            "location":{
              "x":83,
              "y":350},
            "size":{
              "width":63,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF285E8E},
            "cornerRadiusTopLeft":"3",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":1,
              "blurRadius":1,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.0666666666666667}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"717cf0296f2d4080a50056fd40cbd211",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"24px",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF2D6CA2},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF285E8E}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF2D6CA2},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF2B669A}}},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF428BCA},
{
                      "color":0xFF428BCA},
{
                      "color":0xFF2D6CA2},
{
                      "color":0xFF2D6CA2}]},
                "textShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":-1,
                  "blurRadius":0,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.2}},
                "location":{
                  "x":83,
                  "y":350},
                "size":{
                  "width":63,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF285E8E},
                "cornerRadiusTopLeft":"3",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":1,
                  "blurRadius":1,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.0666666666666667}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"wait",
                      "description":"Wait 1 ms",
                      "waitTime":1}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/task/u78.png",
            "mouseOver~":"images/task/u78_mouseOver.png",
            "mouseDown~":"images/task/u78_mouseDown.png"}},
{
          "id":"794c7b7aa86c48b58cb8f5286630dcb0",
          "label":"",
          "type":"repeater",
          "styleType":"repeater",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":463},
            "size":{
              "width":250,
              "height":150}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onItemLoad":{
              "description":"OnItemLoad",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on txtSL equal to &quot;[[Item.SL]]&quot;, and<br> text on txtTaskName equal to &quot;[[Item.Task_Name]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["6a56f87cfa6948b9b3fac4e8fd502ec4"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[Item.SL]]",
                                "localVariables":{
},
                                "stos":[{
                                    "sto":"item",
                                    "name":"sl",
                                    "isTarget":false}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]},
{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["f1dedd11b5f748a7aaf0ebc9bb377e35"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[Item.Task_Name]]",
                                "localVariables":{
},
                                "stos":[{
                                    "sto":"item",
                                    "name":"task_name",
                                    "isTarget":false}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]}},
          "repeaterPropMap":{
            "isolateRadio":true,
            "isolateSelection":true,
            "default":{
              "loadLocalDefault":true,
              "wrap":-1,
              "vertical":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":false,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0},
              "altColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0}},
            "":{
              "width":220,
              "height":30,
              "loadLocalDefault":true,
              "vertical":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "itemsPerPage":5,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0},
              "altColor":{
                "r":204,
                "g":255,
                "b":255,
                "a":1}}},
          "objects":[{
              "id":"8a6c0095974a4ac4a4d2d79ecfcfa38c",
              "label":"txtSL",
              "type":"buttonShape",
              "styleType":"buttonShape",
              "visible":true,
              "style":{
                "size":{
                  "width":50,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6a56f87cfa6948b9b3fac4e8fd502ec4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":50,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/task/txtsl_u81.png"}},
{
              "id":"768a8b5da3f74bb1ad4d7d8d8b5ca3d0",
              "label":"txtTaskName",
              "type":"buttonShape",
              "styleType":"buttonShape",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":50,
                  "y":0},
                "size":{
                  "width":170,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f1dedd11b5f748a7aaf0ebc9bb377e35",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "location":{
                      "x":50,
                      "y":0},
                    "size":{
                      "width":170,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/task/txttaskname_u83.png"}}],
          "data":[{
              "sl":{
                "type":"text",
                "text":"1"},
              "task_name":{
                "type":"text",
                "text":"Buyer Communication"}},
{
              "sl":{
                "type":"text",
                "text":"2"},
              "task_name":{
                "type":"text",
                "text":"Sample Aproval"}},
{
              "sl":{
                "type":"text",
                "text":"3"},
              "task_name":{
                "type":"text",
                "text":"Order Conformation"}}],
          "dataProps":["sl",
"task_name",
"task_process",
"task_function"]},
{
          "id":"827fd58313d34ded889e38b3c98780a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA94442,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFF2DEDE},
{
                  "color":0xFFF2DEDE},
{
                  "color":0xFFEBCCCC},
{
                  "color":0xFFEBCCCC}]},
            "location":{
              "x":83,
              "y":410},
            "size":{
              "width":360,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEBCCD1},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c8689921af7428dbaaf1ecc47152bb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA94442,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFF2DEDE},
{
                      "color":0xFFF2DEDE},
{
                      "color":0xFFEBCCCC},
{
                      "color":0xFFEBCCCC}]},
                "location":{
                  "x":83,
                  "y":410},
                "size":{
                  "width":360,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEBCCD1},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/task/u85.png"}},
{
          "id":"451cc6ad8910470db0f04f4d666fd8d5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":428},
            "size":{
              "width":360,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEBCCD1}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/task/u87_line.png"}},
{
          "id":"06285f01ecc04338a1a043a889fb4855",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":433},
            "size":{
              "width":220,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8853618a99d9462aaf55abce0bebd94a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":50,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eacbd49c478540d4a1fdf5d50e088eeb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":50,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/task/u89.png"}},
{
              "id":"3c640e8def974509a4cf9d6953d6b65e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":50,
                  "y":0},
                "size":{
                  "width":170,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3f70b56192614e939aecfa33df002b32",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":50,
                      "y":0},
                    "size":{
                      "width":170,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/task/u91.png"}}]}]}},
  "masters":{
    "9447b50b9fcc46369087c32d45b2eb92":{
      "packageId":"9447b50b9fcc46369087c32d45b2eb92",
      "type":"Axure:Master",
      "name":"Navigation - Footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"43066f4f84b84c999f4f5ae939adcbe5",
            "label":"Nav - Overview",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Franklin Gothic Book Regular', 'Franklin Gothic Book'",
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xE8E2CA},
              "size":{
                "width":980,
                "height":110},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE8E2CA}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1d27204ba5d3422097491d7c63ad3c32",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Franklin Gothic Book Regular', 'Franklin Gothic Book'",
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xE8E2CA},
                  "size":{
                    "width":980,
                    "height":110},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE8E2CA}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/task/nav_-_overview_u1.png"}},
{
            "id":"0746449051a849e88c866304d9e9939a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Franklin Gothic Book Regular', 'Franklin Gothic Book'",
              "fontSize":"11px",
              "horizontalAlignment":"right",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":430,
                "y":40},
              "size":{
                "width":530,
                "height":15},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ae3b3823f154f95be8261814b0e0870",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Franklin Gothic Book Regular', 'Franklin Gothic Book'",
                  "fontSize":"11px",
                  "horizontalAlignment":"right",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":430,
                    "y":40},
                  "size":{
                    "width":530,
                    "height":15},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bb592eca8a5647a5b1f5833034d2aeee",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Franklin Gothic Book Regular', 'Franklin Gothic Book'",
              "fontSize":"11px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":225,
                "y":80},
              "size":{
                "width":530,
                "height":15},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ae8b40ae007348848a2988c9968f3b7b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Franklin Gothic Book Regular', 'Franklin Gothic Book'",
                  "fontSize":"11px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":225,
                    "y":80},
                  "size":{
                    "width":530,
                    "height":15},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "614f077af181494a913dda5407de8b37":{
      "packageId":"614f077af181494a913dda5407de8b37",
      "type":"Axure:Master",
      "name":"Page Template",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"605db743b3284059a9ccb5dd9fe3f62c",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
              "size":{
                "width":980,
                "height":120}},
            "adaptiveStyles":{
},
            "masterId":"cd9e0e7c2c1d475fb5556f5167e2eed2"},
{
            "id":"d2177a92348a4933be6325fcc3cd564e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":81},
              "size":{
                "width":1390,
                "height":1109},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2c287c13165a4bf0b082aba0b4ddfe6e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":81},
                  "size":{
                    "width":1390,
                    "height":1109},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/task/u22.png"}}]}},
    "cd9e0e7c2c1d475fb5556f5167e2eed2":{
      "packageId":"cd9e0e7c2c1d475fb5556f5167e2eed2",
      "type":"Axure:Master",
      "name":"Navigation - Header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"81c938b822334285a9888f8e12d462da",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Franklin Gothic Book Regular', 'Franklin Gothic Book'",
              "horizontalAlignment":"right",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0033CC,
                "opacity":1},
              "location":{
                "x":944,
                "y":0},
              "size":{
                "width":50,
                "height":17},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3f8dc09a6ebe4a3e94cbd650909c964b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Franklin Gothic Book Regular', 'Franklin Gothic Book'",
                  "horizontalAlignment":"right",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0033CC,
                    "opacity":1},
                  "location":{
                    "x":944,
                    "y":0},
                  "size":{
                    "width":50,
                    "height":17},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"87621b3e11214264ac8e4feedbf2ceee",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":934,
                "y":0},
              "size":{
                "width":10,
                "height":15},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFF3333}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/task/u11_line.png"}},
{
            "id":"9f2052e025df46b0a6e32a0ad3024415",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Franklin Gothic Book Regular', 'Franklin Gothic Book'",
              "horizontalAlignment":"right",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0033CC,
                "opacity":1},
              "location":{
                "x":894,
                "y":0},
              "size":{
                "width":35,
                "height":17},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ecc9a55b9b8342f1a0b1b6b1a9638ffc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Franklin Gothic Book Regular', 'Franklin Gothic Book'",
                  "horizontalAlignment":"right",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0033CC,
                    "opacity":1},
                  "location":{
                    "x":894,
                    "y":0},
                  "size":{
                    "width":35,
                    "height":17},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2e7eaee0d5fc4ca8a2cc1a8af37b812e",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":889,
                "y":0},
              "size":{
                "width":10,
                "height":15},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFF3333}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/task/u11_line.png"}},
{
            "id":"cb12707ea13c42e7b266147bd4f92ab8",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Franklin Gothic Book Regular', 'Franklin Gothic Book'",
              "horizontalAlignment":"right",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0033CC,
                "opacity":1},
              "location":{
                "x":835,
                "y":0},
              "size":{
                "width":49,
                "height":17},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e902292eb0c84de98c476c22e90b8c50",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Franklin Gothic Book Regular', 'Franklin Gothic Book'",
                  "horizontalAlignment":"right",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0033CC,
                    "opacity":1},
                  "location":{
                    "x":835,
                    "y":0},
                  "size":{
                    "width":49,
                    "height":17},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ede20f2200254268a0e62955bb4c427c",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":820,
                "y":0},
              "size":{
                "width":10,
                "height":15},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFF3333}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/task/u11_line.png"}},
{
            "id":"e54cfe20288e4131a1cebf1a78dab487",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Franklin Gothic Book Regular', 'Franklin Gothic Book'",
              "horizontalAlignment":"right",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0033CC,
                "opacity":1},
              "location":{
                "x":650,
                "y":0},
              "size":{
                "width":165,
                "height":17},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68986a5045e943739e1aebd7add46451",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Franklin Gothic Book Regular', 'Franklin Gothic Book'",
                  "horizontalAlignment":"right",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0033CC,
                    "opacity":1},
                  "location":{
                    "x":650,
                    "y":0},
                  "size":{
                    "width":165,
                    "height":17},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"79aa9213b4aa4c27bfbee9df4772957b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Neutraface Slab Text Regular', 'Neutraface Slab Text'",
              "horizontalAlignment":"left",
              "verticalAlignment":"bottom",
              "paddingTop":"0",
              "paddingBottom":"0",
              "location":{
                "x":0,
                "y":15},
              "size":{
                "width":210,
                "height":65},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"82267db647294f509021621e91f8b622",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Neutraface Slab Text Regular', 'Neutraface Slab Text'",
                  "horizontalAlignment":"left",
                  "verticalAlignment":"bottom",
                  "paddingTop":"0",
                  "paddingBottom":"0",
                  "location":{
                    "x":0,
                    "y":15},
                  "size":{
                    "width":210,
                    "height":65},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/financial_app_sample/u16.jpg"}}]}}},
  "objectPaths":{
    "b028ab61ab63406cadd81f09de422ca1":{
      "scriptId":"u0",
      "43066f4f84b84c999f4f5ae939adcbe5":{
        "scriptId":"u1"},
      "1d27204ba5d3422097491d7c63ad3c32":{
        "scriptId":"u2"},
      "0746449051a849e88c866304d9e9939a":{
        "scriptId":"u3"},
      "6ae3b3823f154f95be8261814b0e0870":{
        "scriptId":"u4"},
      "bb592eca8a5647a5b1f5833034d2aeee":{
        "scriptId":"u5"},
      "ae8b40ae007348848a2988c9968f3b7b":{
        "scriptId":"u6"}},
    "15880db42c004553a88490d8e863e8e4":{
      "scriptId":"u7",
      "605db743b3284059a9ccb5dd9fe3f62c":{
        "scriptId":"u8",
        "81c938b822334285a9888f8e12d462da":{
          "scriptId":"u9"},
        "3f8dc09a6ebe4a3e94cbd650909c964b":{
          "scriptId":"u10"},
        "87621b3e11214264ac8e4feedbf2ceee":{
          "scriptId":"u11"},
        "9f2052e025df46b0a6e32a0ad3024415":{
          "scriptId":"u12"},
        "ecc9a55b9b8342f1a0b1b6b1a9638ffc":{
          "scriptId":"u13"},
        "2e7eaee0d5fc4ca8a2cc1a8af37b812e":{
          "scriptId":"u14"},
        "cb12707ea13c42e7b266147bd4f92ab8":{
          "scriptId":"u15"},
        "e902292eb0c84de98c476c22e90b8c50":{
          "scriptId":"u16"},
        "ede20f2200254268a0e62955bb4c427c":{
          "scriptId":"u17"},
        "e54cfe20288e4131a1cebf1a78dab487":{
          "scriptId":"u18"},
        "68986a5045e943739e1aebd7add46451":{
          "scriptId":"u19"},
        "79aa9213b4aa4c27bfbee9df4772957b":{
          "scriptId":"u20"},
        "82267db647294f509021621e91f8b622":{
          "scriptId":"u21"}},
      "d2177a92348a4933be6325fcc3cd564e":{
        "scriptId":"u22"},
      "2c287c13165a4bf0b082aba0b4ddfe6e":{
        "scriptId":"u23"}},
    "cae31c4f3f9a489e9d23a55b2aa13905":{
      "scriptId":"u24"},
    "69cc2d442f7b4d669cb50029b31fece2":{
      "scriptId":"u25"},
    "aa4b9b62846a40efbf50db7643b5ad56":{
      "scriptId":"u26"},
    "b76dcd1b20ba481bb36c7dfb7e2ff458":{
      "scriptId":"u27"},
    "a0fe908ca2234f3cbc549932c17c8c66":{
      "scriptId":"u28"},
    "d1c59a7c7c974be7bf98a9551e3f538d":{
      "scriptId":"u29"},
    "b04968727065451d96f5e3b07d1aefb8":{
      "scriptId":"u30"},
    "144c1bbc41684d46a7367a5be599aa04":{
      "scriptId":"u31"},
    "8b3f3e30ee954a6da750d7007c17e92b":{
      "scriptId":"u32"},
    "8cab25fee0c54bb6815b48c36e5b7353":{
      "scriptId":"u33"},
    "cdef5756f6d04f7ab2b0ed5e9c9efc2a":{
      "scriptId":"u34"},
    "8fe1f06653284a77b5ba30d9be2956ff":{
      "scriptId":"u35"},
    "4ebf4989ca3644bcbde26fd9789e3afd":{
      "scriptId":"u36"},
    "93ff4253be534b03bbc4af5499e6c7b5":{
      "scriptId":"u37"},
    "c3527ca89326446aae2395242cca8a32":{
      "scriptId":"u38"},
    "7f8b0d0cf4944c3fbbbb801c50277c55":{
      "scriptId":"u39"},
    "52f253b79fd14675851bcdda2ae97ed8":{
      "scriptId":"u40"},
    "e42ec42f062540f49098654b718d9b28":{
      "scriptId":"u41"},
    "b2e6836015444582b21f99f8ac8f95eb":{
      "scriptId":"u42"},
    "40a5b160d4bf48b88147515eb20cde77":{
      "scriptId":"u43"},
    "59f6b77b42c34d38a98df44346323ba0":{
      "scriptId":"u44"},
    "796fbdf68af946ed805e44a6c0443e8c":{
      "scriptId":"u45"},
    "e39df351a70547dfad628ab6ab6253a8":{
      "scriptId":"u46"},
    "207a950a8aff484fa4d3b841dc55d935":{
      "scriptId":"u47"},
    "c311d78971c0464d8166c2c413349c62":{
      "scriptId":"u48"},
    "1df7e41a24e142edb11e2e006071f21d":{
      "scriptId":"u49"},
    "087a83edbb894cd89e6d849c4008320e":{
      "scriptId":"u50"},
    "7afc47f3bbc3411f946e61c884a47d04":{
      "scriptId":"u51"},
    "8e6765e627924027a2f89801b1b00072":{
      "scriptId":"u52"},
    "e830202f19dd4e6d8d699f89a5cb5fa2":{
      "scriptId":"u53"},
    "ec9df1d67acc427e8ef999ed12541343":{
      "scriptId":"u54"},
    "3f04f63984e04f0494e11806ae0670c7":{
      "scriptId":"u55"},
    "fdefa150f1fc4cdca3acafd5b85383ff":{
      "scriptId":"u56"},
    "f09f1508fe1a425f96d2da06522d987f":{
      "scriptId":"u57"},
    "d07dd707b1014df5b1af15cb6a8a76fb":{
      "scriptId":"u58"},
    "cf008d9b7dec4c89a210136ef14de73e":{
      "scriptId":"u59"},
    "d0987333a6ca44ce87eba44b6f4bee8d":{
      "scriptId":"u60"},
    "5e2ec0954d8644d9bafc18cfb86c1684":{
      "scriptId":"u61"},
    "283a266e01404483a23b75805712a561":{
      "scriptId":"u62"},
    "1815089b6f37437a944fb46a688f89b5":{
      "scriptId":"u63"},
    "0f907b34723c4ddcb972dbd49518180b":{
      "scriptId":"u64"},
    "23ea19e717444f6f955efd85be69b8cf":{
      "scriptId":"u65"},
    "7b2e3ae8a34340c1aad8a2193cd40dca":{
      "scriptId":"u66"},
    "00b7942340af4ae0a615c6eb7c426ab1":{
      "scriptId":"u67"},
    "067075349c314d059e5629a13b04e9e7":{
      "scriptId":"u68"},
    "aa4e52a24acb422f8fdbf03da12449b3":{
      "scriptId":"u69"},
    "10e5a16f8a3c4f819a8fcb1ea2e04c49":{
      "scriptId":"u70"},
    "72bc9c4fddce4b7fb09a540dc398b9a0":{
      "scriptId":"u71"},
    "36857b1e92584183a1cdf7a0c092d4d7":{
      "scriptId":"u72"},
    "3b22dd93583b4de9b349bcc0ea4bc0ed":{
      "scriptId":"u73"},
    "83cc23c470224eb0a3a30fb911fc204c":{
      "scriptId":"u74"},
    "4733add2122842df93a3e3d95c6f0c6f":{
      "scriptId":"u75"},
    "fdb951f56fce44f9929893d56aeb4b40":{
      "scriptId":"u76"},
    "75a21926458145e98aadcf675a3e8a05":{
      "scriptId":"u77"},
    "e99aeb01288540dea91e0b1c8c8b1527":{
      "scriptId":"u78"},
    "717cf0296f2d4080a50056fd40cbd211":{
      "scriptId":"u79"},
    "794c7b7aa86c48b58cb8f5286630dcb0":{
      "scriptId":"u80"},
    "8a6c0095974a4ac4a4d2d79ecfcfa38c":{
      "scriptId":"u81"},
    "6a56f87cfa6948b9b3fac4e8fd502ec4":{
      "scriptId":"u82"},
    "768a8b5da3f74bb1ad4d7d8d8b5ca3d0":{
      "scriptId":"u83"},
    "f1dedd11b5f748a7aaf0ebc9bb377e35":{
      "scriptId":"u84"},
    "827fd58313d34ded889e38b3c98780a1":{
      "scriptId":"u85"},
    "4c8689921af7428dbaaf1ecc47152bb6":{
      "scriptId":"u86"},
    "451cc6ad8910470db0f04f4d666fd8d5":{
      "scriptId":"u87"},
    "06285f01ecc04338a1a043a889fb4855":{
      "scriptId":"u88"},
    "8853618a99d9462aaf55abce0bebd94a":{
      "scriptId":"u89"},
    "eacbd49c478540d4a1fdf5d50e088eeb":{
      "scriptId":"u90"},
    "3c640e8def974509a4cf9d6953d6b65e":{
      "scriptId":"u91"},
    "3f70b56192614e939aecfa33df002b32":{
      "scriptId":"u92"}}});