# -*- coding: utf-8 -*-

{
    'name': 'Member Installation',
    'author': 'Genweb2 Limited',
    'website': 'www.genweb2.com',
    'category': 'Module Installation',
    'summary': 'Install all member related module',
    'description': 'Install all member related module',
    'version': '1.0',
    'depends': [
        "member_card_replacement",
        "member_payment",
        "member_renew",
        "member_signup",
        "member_user",
        "membership",
        "membership_card",
        "membership_extension",
        "membership_remaining_days",
        "membership_variable_period",
        "membership_withdrawal",
        "member_card_replacement",
        "member_payment",
        "member_renew",
        "member_signup",
        "member_user",
        "membership",
        "membership_card",
        "membership_extension",
        "membership_remaining_days",
        "membership_variable_period",
        "membership_withdrawal",
    ],
    'installable': True,
    'application': True,
}
