{
    'name': 'GBS HR Attendance Report',
    'author': 'Genweb2 Limited',
    'website': 'www.genweb2.com',
    'category': 'attendance',
    'version': '10.0.1.0.0',
    'depends': [
        'hr_attendance',
        'hr',
        'gbs_operating_unit',
        'gbs_hr_employee',
        'hr_employee_operating_unit',
        'gbs_hr_attendance_utility',
        #'gbs_hr_device_config',
        'report_layout',
        'hr_attendance_and_ot_summary'
    ],
    'data': [
        'security/ir.model.access.csv',
        #'security/ir_rule.xml',
        'report/report_paperformat.xml',
        #'report/gbs_hr_attendance_report.xml',
        'wizard/hr_attendance_duration_wizard_views.xml',
        'report/gbs_hr_attendance_duration_report.xml',
        #'report/daily_attendance_report.xml',
        #'report/daily_attendance_report_templates.xml',
        'report/hr_daily_attendance_report_template.xml',
        'wizard/hr_attendance_report_wizard_views.xml',
        #'wizard/daily_attendance_report_wizard_view.xml',
        'wizard/hr_daily_attendance_report_wizard_views.xml',
        'wizard/attendance_error_summary.xml',
        'report/gbs_hr_attendance_report_template.xml',
        'report/attendance_error_summary_report.xml',
        'wizard/employee_attendance_wizard.xml',
        'report/gbs_employee_attendance_report_template.xml',
        'report/attendance_summary_report_view.xml',
        'report/attendance_summary_report_template.xml',
        'wizard/attendance_summary_report_wizard_view.xml'
    ],

    'summary': 'Generates check in and check out related report of employee(s)',
    'description': 'Generates check in and check out related report of employee(s)',
    'installable': True,
    'application': True,
}
