# -*- coding: utf-8 -*-

{
    'name': 'EMK Menu',
    'author': 'Genweb2 Limited',
    'website': 'www.genweb2.com',
    'category': 'EMK Menu',
    'version': '10.0.1.0.0',
    'category': 'Menu',
    'summary': '',
    'description': '',
    'depends': [
        'hr',
        'hr_payroll',
        'hr_holidays',
        'hr_recruitment',
        'hr_attendance',
        'stock',
        'calendar',
        'mail',
        'utm',
        'survey',
        'hr_contract',
        'hr_employee_iou',
        'hr_payroll_arrear',
        'hr_employee_mobile_bills',
        'hr_employee_meal_bills',
        'hr_employee_iou',
        'hr_other_allowance',
        'hr_experience',
        'point_of_sale',
        'event',
        'membership',
        'account_asset',
        'account',
        'purchase',
        'appointment_menu',
    ],
    'data': [
        'views/main_menu_view.xml',
        'views/hr_menu_view.xml',
    ],
    'installable': True,
    'application': True,
}
