# -*- coding: utf-8 -*-

{
    'name': 'EMK Installation',
    'author': 'Genweb2 Limited',
    'website': 'www.genweb2.com',
    'category': 'EMK Installation',
    'version': '1.0',
    'data': [],
    'depends': [
        'app_odoo_customize',
        'pos_reprint',
        'stock',
        'stock_account',
        'point_of_sale',
        'mail',
        'hr_holidays',
        'account',
        'account_asset',
        'account_accountant',
        'hr_payroll',
        'website',
        'website_sale',
        'purchase',
        'hr',
        'hr_recruitment',
        'hr_expense',
        'pos_data_drinks',
        'account_bank_statement_import',
        'account_budget',
        'analytic',
        'association',
        'auth_crypt',
        'auth_session_timeout',
        'auth_signup',
        'auto_backup',
        'barcodes',
        'database_cleanup',
        'decimal_precision',
        'document',
        'event',
        'event_contact',
        'event_mail',
        'event_registration_mass_mailing',
        'event_sale',
        'event_session',
        'fetchmail',
        'hidden_admin',
        'hr_contract',
        'hr_emergency_contact',
        'hr_employee_blood_group',
        'hr_employee_number',
        'hr_employee_seniority',
        'hr_family',
        'hr_payroll_account',
        'ir_rule_protected',
        'link_tracker',
        'mass_editing',
        'membership',
        'membership_card',
        'membership_extension',
        'membership_initial_fee',
        'membership_remaining_days',
        'membership_variable_period',
        'membership_withdrawal',
        'partner_contact_birthdate',
        'partner_contact_gender',
        'partner_contact_nationality',
        'partner_contact_personal_information_page',
        'partner_firstname',
        'partner_second_lastname',
        'payment',
        'payment_transfer',
        'portal',
        'portal_sale',
        'portal_stock',
        'procurement',
        'procurement_jit',
        'product',
        'rating',
    ],
    'category': 'Installation Module',
    'summary': 'Install Module of EMK',
    'description': 'Install Module of EMK',
    'installable': True,
    'application': True,
}
