{
    'name': 'HR Public Holidays',
    'version': '10.0.1.0.0',
    'sequence': 30,
    'category': 'Human Resources',
    'author': 'Genweb2 Limited',
    'website': 'www.genweb2.com',
    'summary': "Manage All kinds of Holidays",
    'depends': [
        'hr',
        'hr_holidays',
        'hr_payroll',
        # 'gbs_hr_calendar',
        'operating_unit',
        'hr_rostering',
        'hr_holiday_year',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'wizard/hr_calendar_clone_wizard_view.xml',
        'wizard/hr_holidays_exception_wizard_view.xml',
        'views/hr_public_holidays_view.xml',
        'views/hr_holidays_calendar_view.xml',
        'views/hr_holidays_exception_employee_batch_view.xml',
    ],
    'installable': True,
    'application': True,
}
