{
    'name': 'GBS Accounting Installer',
    'version': '10.0.1.0.0',
    'author': 'Genweb2 Limited',
    'website': 'http://www.genweb2.com',
    'category': 'Installation',
    'depends': [
        "account",
        "account_accountant",
        "account_parent",
        "account_operating_unit",
        "account_asset",
        "account_fam",
        "account_fiscal_month",
        "agreement_account",
        "date_range",
        "account_type_menu",
        "base_vat_bd",
        "account_fiscal_year",
        "account_invoice_merge_operating_unit",
        "account_invoice_merge_attachment",
        "account_tds",
        "account_mtbl",
    ],
    'description': 'Install all modules which is related to MTBL Accounting',
    'installable': True,
    'application': True,
}
