# -*- coding: utf-8 -*-

{
    'name': 'Install All Modules for EMK Organization',
    'author': 'Genweb2 Limited',
    'website': 'www.genweb2.com',
    'category': 'Module Installation',
    'summary': 'Install Module of EMK',
    'description': 'Install Module of EMK',
    'version': '1.0',
    'depends': [
        'emk_menu',
        'install_inventory',
        'install_appointment',
        'install_cafeteria',
        'install_event',
        'install_hr',
        'install_member',
        "ir_sequence_operating_unit",
        "amount_to_word_bd",
        "auth_admin_passkey",
        "auth_crypt",
        "auth_signup",
        "barcodes",
        "base_action_rule",
        "base_bank_bd",
        "base_suspend_security",
        "base_technical_features",
        "birthday_wish",
        "create_partner_user",
        "data_import",
        "date_range",
        "decimal_precision",
        "disable_odoo_online",
        "gbs_operating_unit",
        "gbs_res_users",
        "hide_desktop_notification_link",
        "login_access_error",
        "mail_send",
        "mass_editing",
        "opa_utility",
        "operating_unit",
        "partner_fullname",
        "payment",
        "payment_transfer",
        "portal",
        "procurement",
        "product",
        "report_layout",
        "resource",
        "server_action_permission",
        "tko_account",
        "tko_account_configuration",
        "tko_account_multi_company",
        "tko_account_payment_term_fixed_day",
        "web_hide_db_poweredby_link",
        "web_settings_dashboard",
        "website_event_filter_selector",
        "website_hr_recruitment",
        "website_mail",
        "website_partner",
        "account_configuration",
    ],
    'installable': True,
    'application': True,
}
