# -*- coding: utf-8 -*-

{
    'name': 'Install All Modules for EMK Organization',
    'author': 'Genweb2 Limited',
    'website': 'www.genweb2.com',
    'category': 'Module Installation',
    'summary': 'Install Module of EMK',
    'description': 'Install Module of EMK',
    'version': '1.0',
    'depends': [
        # 'emk_menu',
        # 'install_inventory',
        # 'install_appointment',
        # 'install_cafeteria',
        # 'install_event',
        # 'install_hr',
        # 'install_member',
        # "ir_sequence_operating_unit",
        # "amount_to_word_bd",
        # "auth_admin_passkey",
        # "auth_crypt",
        # "auth_signup",
        # "barcodes",
        # "base_action_rule",
        # "base_bank_bd",
        # "base_suspend_security",
        # "base_technical_features",
        # "birthday_wish",
        # "create_partner_user",
        # "data_import",
        # "date_range",
        # "decimal_precision",
        # "disable_odoo_online",
        # "gbs_operating_unit",
        # "gbs_res_users",
        # "hide_desktop_notification_link",
        # "login_access_error",
        # "mail_send",
        # "mass_editing",
        # "opa_utility",
        # "operating_unit",
        # "partner_fullname",
        # "payment",
        # "payment_transfer",
        # "portal",
        # "procurement",
        # "product",
        # "report_layout",
        # "resource",
        # "server_action_permission",
        # "tko_account",
        # "tko_account_configuration",
        # "tko_account_multi_company",
        # "tko_account_payment_term_fixed_day",
        # "web_hide_db_poweredby_link",
        # "web_settings_dashboard",
        # "website_event_filter_selector",
        # "website_hr_recruitment",
        # "website_mail",
        # "website_partner",
        # "account_configuration",
        "ir_sequence_operating_unit",
        "amount_to_word_bd",
        "pos_discount",
        "pos_operating_unit",
        "pos_reprint",
        "account_fam_access",
        "account_fam_install",
        "account_fam_menu",
        "appointment_menu",
        "emk_purchase_order_access",
        "emk_purchase_order_install",
        "emk_purchase_order_menu",
        "stock_indent_access",
        "stock_indent_install",
        "stock_indent_menu",
        "stock",
        "sale",
        "stock_account",
        "point_of_sale",
        "mail",
        "hr_short_leave",
        "hr_holidays",
        "account",
        "gbs_hr_leave_duration_correction",
        "gbs_hr_public_holidays",
        "hr_holiday_exception",
        "account_asset",
        "account_accountant",
        "hr_payroll",
        "website",
        "birth_day_notification",
        "gbs_hr_holiday_hour",
        "purchase",
        "hr",
        "hr_attendance",
        "hr_recruitment",
        "gbs_hr_department_sequence",
        "account_bank_statement_import",
        "account_configuration",
        "account_fam",
        "account_fam_category",
        "account_fam_vendor_bills",
        "account_fiscal_month",
        "account_fiscal_year",
        "account_operating_unit",
        "account_parent",
        "analytic",
        "analytic_operating_unit",
        "appointment_user",
        "appointments",
        "auth_admin_passkey",
        "auth_crypt",
        "auth_signup",
        "barcodes",
        "base",
        "base_action_rule",
        "base_bank_bd",
        "base_import",
        "base_setup",
        "base_suspend_security",
        "base_technical_features",
        "base_vat_bd",
        "birthday_wish",
        "bus",
        "create_partner_user",
        "create_users",
        "data_import",
        "date_range",
        "decimal_precision",
        "disable_odoo_online",
        "document",
        "emk_hr",
        "emk_menu",
        "emk_payment",
        "emk_purchase_order",
        "employee_stages",
        "event",
        "event_mail",
        "event_management",
        "event_payment",
        "event_sale",
        "event_sessions",
        "event_user",
        "fetchmail",
        "gbs_application_group",
        "gbs_base_package",
        "gbs_data_migration",
        "gbs_gender",
        "gbs_hr_attendance",
        "gbs_hr_attendance_error_correction",
        "gbs_hr_attendance_grace_time",
        "gbs_hr_attendance_report",
        "gbs_hr_attendance_utility",
        "gbs_hr_device_config",
        "gbs_hr_employee",
        "gbs_hr_employee_documents",
        "gbs_hr_employee_security",
        "gbs_hr_job_extend",
        "gbs_hr_leave_report",
        "gbs_hr_package",
        "gbs_hr_payroll",
        "gbs_hr_recruitment",
        "gbs_hr_recruitment_access_rights",
        "gbs_hr_security",
        "gbs_operating_unit",
        "gbs_res_users",
        "gbs_sale_quotation_number",
        "gbs_stock_product",
        "hide_desktop_notification_link",
        "hr_absence_summary",
        "hr_attendance_and_ot_summary",
        "hr_attendance_dashboard",
        "hr_attendance_import",
        "hr_attendance_store",
        "hr_contract",
        "hr_contract_reference",
        "hr_earned_leave",
        "hr_employee_attendance_payroll",
        "hr_employee_exit",
        "hr_employee_iou",
        "hr_employee_iou_payroll",
        "hr_employee_loan",
        "hr_employee_loan_payroll",
        "hr_employee_meal_bills",
        "hr_employee_meal_bills_payroll",
        "hr_employee_mobile_bills",
        "hr_employee_mobile_bills_payroll",
        "hr_employee_number",
        "hr_employee_seniority",
        "hr_experience",
        "hr_family",
        "hr_holiday_utility",
        "hr_holiday_year",
        "hr_holidays_compute_days",
        "hr_holidays_multi_approval_notification",
        "hr_holidays_multi_levels_approval",
        "hr_manual_attendance",
        "hr_other_allowance",
        "hr_other_allowance_payroll",
        "hr_overtime_requisition",
        "hr_payroll_arrear",
        "hr_payroll_festival_bonus",
        "hr_public_holidays",
        "hr_recruitment_survey",
        "hr_rostering",
        "indent_type",
        "install_appointment",
        "install_cafeteria",
        "install_emk",
        "install_event",
        "install_hr",
        "install_inventory",
        "install_member",
        "inventory_user",
        "l10n_generic_coa",
        "l10n_in_hr_payroll",
        "login_access_error",
        "mail_send",
        "mass_editing",
        "member_card_replacement",
        "member_payment",
        "member_renew",
        "member_signup",
        "member_user",
        "membership",
        "membership_card",
        "membership_extension",
        "membership_remaining_days",
        "membership_variable_period",
        "membership_withdrawal",
        "opa_utility",
        "operating_unit",
        "partner_fullname",
        "payment",
        "payment_transfer",
        "portal",
        "portal_sale",
        "portal_stock",
        "procurement",
        "procurement_jit",
        "product",
        "report",
        "report_layout",
        "resource",
        "sale_stock",
        "sales_team",
        "server_action_permission",
        "stock_indent",
        "stock_operating_unit",
        "stock_operating_unit_user",
        "tko_account",
        "tko_account_configuration",
        "tko_account_multi_company",
        "tko_account_payment_term_fixed_day",
        "utm",
        "web",
        "web_calendar",
        "web_diagram",
        "web_editor",
        "web_hide_db_poweredby_link",
        "web_kanban",
        "web_kanban_gauge",
        "web_planner",
        "web_settings_dashboard",
        "web_tour",
        "website_event_filter_selector",
        "website_event_questions",
        "website_form",
        "website_hr_recruitment",
        "website_mail",
        "website_partner",
        "website_theme_install",
        "hr_attendance_settings",
        "hr_employee_operating_unit",
        "survey",
        "calendar",
        "event_registration",
        "website_event",
    ],
    'installable': True,
    'application': True,
}
